/**
 * Order Status Constants (Mirroring DB Enum)
 */
export const OrderStatus = {
    PENDING: 'PENDING',
    RESERVED: 'RESERVED',
    HELD: 'HELD',
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    PAID: 'PAID',
    PROCESSING: 'PROCESSING',
    SERVICE_PENDING: 'SERVICE_PENDING',
    DELIVERY_PENDING: 'DELIVERY_PENDING',
    COLLECTION_PENDING: 'COLLECTION_PENDING',
    FULFILLMENT_PENDING: 'FULFILLMENT_PENDING',
    FULFILLED: 'FULFILLED',
    DELIVERED: 'DELIVERED',
    BOOKED: 'BOOKED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    FAILED: 'FAILED',
    EXPIRED: 'EXPIRED',
    REFUND_PENDING: 'REFUND_PENDING',
    REFUNDED: 'REFUNDED',
    COMPENSATION_REQUIRED: 'COMPENSATION_REQUIRED'
};

export const OrderType = {
    PHYSICAL: 'PHYSICAL',
    SERVICE: 'SERVICE',
    DIGITAL: 'DIGITAL'
};

export const FulfillmentType = {
    BUYER_TO_SELLER: 'BUYER_TO_SELLER',
    COURIER: 'COURIER',
    SELLER_TO_BUYER: 'SELLER_TO_BUYER',
    DIGITAL: 'DIGITAL'
};
