-- Migration: Re-Sync Order Status Enum
-- Reason: Ensure all statuses are added and COMMITTED before they are used in complex migrations.
-- This file must run before 191000 overhaul.

ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'CREATED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'RESERVED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'HELD';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PAYMENT_PENDING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PAID';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'SERVICE_PENDING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'DELIVERY_PENDING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'COLLECTION_PENDING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'FULFILLMENT_PENDING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'FULFILLED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'BOOKED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'REFUND_PENDING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'REFUNDED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'COMPENSATION_REQUIRED';
