-- Unified runtime schema upgrade for Byblos.
-- Goal: align the database with the columns and constraints referenced by the
-- current codebase, while keeping the migration idempotent.

-- Core roles / users
CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    slug VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_permissions (
    id SERIAL PRIMARY KEY,
    role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE,
    permission_id INTEGER REFERENCES permissions(id) ON DELETE CASCADE,
    UNIQUE(role_id, permission_id)
);

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_login TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS reset_password_token VARCHAR(255),
    ADD COLUMN IF NOT EXISTS reset_password_expires TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS email_verification_token VARCHAR(255),
    ADD COLUMN IF NOT EXISTS email_verification_expires TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_users_email
    ON public.users(LOWER(email));

-- Buyer / seller / creator profiles
ALTER TABLE public.buyers
    ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS refunds NUMERIC(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS is_member BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS member_number INTEGER,
    ADD COLUMN IF NOT EXISTS membership_joined_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE SEQUENCE IF NOT EXISTS byblos_member_seq START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX IF NOT EXISTS buyers_member_number_key
    ON public.buyers(member_number)
    WHERE member_number IS NOT NULL;

ALTER TABLE public.sellers
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS balance NUMERIC(15, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS client_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pending_settlement_balance NUMERIC(15, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS withdrawal_reserved_balance NUMERIC(15, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS refund_reserved_balance NUMERIC(15, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS instagram_link TEXT,
    ADD COLUMN IF NOT EXISTS tiktok_link TEXT,
    ADD COLUMN IF NOT EXISTS facebook_link TEXT,
    ADD COLUMN IF NOT EXISTS terms_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.creators
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS balance NUMERIC(15, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS withdrawal_reserved_balance NUMERIC(15, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS refund_withdrawal_reserved_balance NUMERIC(15, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS whatsapp_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS mpesa_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- Products and product orders
ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS aesthetic VARCHAR(50),
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'available',
    ADD COLUMN IF NOT EXISTS product_type VARCHAR(20) NOT NULL DEFAULT 'physical',
    ADD COLUMN IF NOT EXISTS is_digital BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS digital_file_path TEXT,
    ADD COLUMN IF NOT EXISTS digital_file_name TEXT,
    ADD COLUMN IF NOT EXISTS digital_file_size INTEGER,
    ADD COLUMN IF NOT EXISTS service_locations JSONB,
    ADD COLUMN IF NOT EXISTS service_options JSONB,
    ADD COLUMN IF NOT EXISTS track_inventory BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reserved_quantity INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.product_orders
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50) DEFAULT 'paystack',
    ADD COLUMN IF NOT EXISTS buyer_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS buyer_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS buyer_mobile_payment VARCHAR(50),
    ADD COLUMN IF NOT EXISTS buyer_whatsapp_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS shipping_address TEXT,
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS metadata JSONB,
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS payment_status public.payment_status NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS service_requirements TEXT,
    ADD COLUMN IF NOT EXISTS is_debt BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS client_id INTEGER,
    ADD COLUMN IF NOT EXISTS is_seller_initiated BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS fulfillment_type fulfillment_type DEFAULT 'BUYER_TO_SELLER',
    ADD COLUMN IF NOT EXISTS delivery_location JSONB,
    ADD COLUMN IF NOT EXISTS order_type order_type DEFAULT 'PHYSICAL',
    ADD COLUMN IF NOT EXISTS total_quantity INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS reservation_expires_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS location_address TEXT,
    ADD COLUMN IF NOT EXISTS location_lat NUMERIC(10, 8),
    ADD COLUMN IF NOT EXISTS location_lng NUMERIC(11, 8),
    ADD COLUMN IF NOT EXISTS service_title TEXT,
    ADD COLUMN IF NOT EXISTS notification_sent BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS auto_cancelled_reason TEXT,
    ADD COLUMN IF NOT EXISTS pre_handoff_sla JSONB,
    ADD COLUMN IF NOT EXISTS client_checkout_token VARCHAR(255),
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS seller_dropoff_deadline TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS buyer_pickup_deadline TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS ready_for_pickup_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS custom_production_deadline_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS custom_production_grace_deadline_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS custom_production_reminder_sent_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_product_orders_paid_at
    ON public.product_orders(paid_at);
CREATE INDEX IF NOT EXISTS idx_orders_notification_sent
    ON public.product_orders(notification_sent);

-- Payments / settlements / withdrawals
ALTER TABLE public.payments
    ADD COLUMN IF NOT EXISTS status public.payment_status NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50) DEFAULT 'paystack',
    ADD COLUMN IF NOT EXISTS mobile_payment VARCHAR(50),
    ADD COLUMN IF NOT EXISTS whatsapp_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS metadata JSONB,
    ADD COLUMN IF NOT EXISTS provider_reference VARCHAR(255),
    ADD COLUMN IF NOT EXISTS api_ref VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mpesa_receipt VARCHAR(50),
    ADD COLUMN IF NOT EXISTS raw_response JSONB,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS payouts (
    id SERIAL PRIMARY KEY,
    seller_id INTEGER REFERENCES sellers(id) ON DELETE SET NULL,
    order_id INTEGER UNIQUE REFERENCES product_orders(id) ON DELETE CASCADE,
    payment_id INTEGER REFERENCES payments(id) ON DELETE SET NULL,
    amount NUMERIC(15, 2) NOT NULL CHECK (amount >= 0),
    platform_fee NUMERIC(15, 2) NOT NULL DEFAULT 0 CHECK (platform_fee >= 0),
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    payment_method VARCHAR(50),
    processed_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    available_at TIMESTAMP WITH TIME ZONE,
    settled_at TIMESTAMP WITH TIME ZONE,
    settlement_status VARCHAR(30) NOT NULL DEFAULT 'settled',
    settlement_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS withdrawal_requests (
    id SERIAL PRIMARY KEY,
    seller_id INTEGER REFERENCES sellers(id) ON DELETE CASCADE,
    creator_id INTEGER REFERENCES creators(id) ON DELETE CASCADE,
    buyer_id INTEGER REFERENCES buyers(id) ON DELETE CASCADE,
    amount NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    mpesa_number VARCHAR(50) NOT NULL,
    mpesa_name VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'processing',
    provider_reference VARCHAR(255),
    mpesa_receipt VARCHAR(80),
    raw_response JSONB DEFAULT '{}'::jsonb,
    metadata JSONB DEFAULT '{}'::jsonb,
    api_call_pending BOOLEAN DEFAULT FALSE,
    idempotency_key VARCHAR(120) NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE,
    processed_by VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Logistics runtime tables
ALTER TABLE public.logistics_partners
    ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS name VARCHAR(160),
    ADD COLUMN IF NOT EXISTS slug VARCHAR(160),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS whatsapp_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS logistics_partners_slug_unique
    ON public.logistics_partners(slug);

ALTER TABLE public.logistics_requests
    ADD COLUMN IF NOT EXISTS order_id INTEGER REFERENCES product_orders(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS partner_id BIGINT REFERENCES logistics_partners(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS package_code VARCHAR(80),
    ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS service_level VARCHAR(40) NOT NULL DEFAULT 'standard',
    ADD COLUMN IF NOT EXISTS deadline_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.logistics_legs
    ADD COLUMN IF NOT EXISTS logistics_request_id BIGINT REFERENCES logistics_requests(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS leg_type VARCHAR(20),
    ADD COLUMN IF NOT EXISTS payer VARCHAR(20),
    ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL DEFAULT 'payment_pending',
    ADD COLUMN IF NOT EXISTS payment_id INTEGER REFERENCES payments(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS fee_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fee_currency VARCHAR(10) NOT NULL DEFAULT 'KES',
    ADD COLUMN IF NOT EXISTS distance_km NUMERIC(10, 2),
    ADD COLUMN IF NOT EXISTS origin_label VARCHAR(160),
    ADD COLUMN IF NOT EXISTS origin_address TEXT,
    ADD COLUMN IF NOT EXISTS origin_lat NUMERIC(10, 8),
    ADD COLUMN IF NOT EXISTS origin_lng NUMERIC(11, 8),
    ADD COLUMN IF NOT EXISTS destination_label VARCHAR(160),
    ADD COLUMN IF NOT EXISTS destination_address TEXT,
    ADD COLUMN IF NOT EXISTS destination_lat NUMERIC(10, 8),
    ADD COLUMN IF NOT EXISTS destination_lng NUMERIC(11, 8),
    ADD COLUMN IF NOT EXISTS deadline_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS failed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.logistics_tracking_events
    ADD COLUMN IF NOT EXISTS logistics_request_id BIGINT REFERENCES logistics_requests(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS logistics_leg_id BIGINT,
    ADD COLUMN IF NOT EXISTS event_key VARCHAR(255),
    ADD COLUMN IF NOT EXISTS event_type VARCHAR(80) NOT NULL,
    ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL,
    ADD COLUMN IF NOT EXISTS message TEXT,
    ADD COLUMN IF NOT EXISTS source VARCHAR(40) NOT NULL DEFAULT 'system',
    ADD COLUMN IF NOT EXISTS actor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS actor_label VARCHAR(160),
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS logistics_tracking_events_event_key_unique
    ON public.logistics_tracking_events(event_key)
    WHERE event_key IS NOT NULL;

ALTER TABLE public.logistics_tracking_links
    ADD COLUMN IF NOT EXISTS logistics_request_id BIGINT REFERENCES logistics_requests(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS audience VARCHAR(20),
    ADD COLUMN IF NOT EXISTS public_id VARCHAR(64),
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- Membership, notifications, and account-support tables
CREATE SEQUENCE IF NOT EXISTS byblos_member_seq START WITH 1 INCREMENT BY 1;

-- Backfill defaults for rows created before these columns existed.
UPDATE public.users SET is_active = COALESCE(is_active, TRUE) WHERE is_active IS NULL;
UPDATE public.buyers SET refunds = COALESCE(refunds, 0) WHERE refunds IS NULL;
UPDATE public.buyers SET status = COALESCE(NULLIF(status, ''), 'active');
UPDATE public.sellers SET status = COALESCE(NULLIF(status, ''), 'active');
UPDATE public.creators SET status = COALESCE(NULLIF(status, ''), 'active');
